;db 셋팅
[db]
host   = localhost
dbid   = ssss01047271791
dbpass = "Shinsoo1993!"
dbname = ssss01047271791
port   =

;pg사 관련 셋팅
[pg]
mertkey = e57352760ea5a2a1fce315c6ead11ece
cst_mid = shinsoo
cst_platform = service
